name: calculator_modularization_di
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.1

  calculator_modularization_data:
    path: ../data
  calculator_modularization_domain:
    path: ../domain
  calculator_modularization_presentation:
    path: ../presentation

dev_dependencies:
  flutter_lints: 3.0.1